server:
  port: 9090

# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode : false
  bowerMode : false
  disableUsageStatistics : true

# Workaround for https://github.com/vaadin/flow/issues/5947
spring:
  # Uncomment if using PostgreSQL
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/xfinance_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
     ddl-auto: update
      #ddl-auto: create-drop
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        enable_lazy_load_no_trans: true
    open-in-view: false

  # enable H2 web console and set url for web console
  # http://localhost:8080/console

logging:
  level:
    org:
      atmosphere : warn

