server:
  port: 9090

# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode : false
  bowerMode : false
  disableUsageStatistics : true

# Workaround for https://github.com/vaadin/flow/issues/5947
spring:
  # Uncomment if using PostgreSQL
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/tu_inventario_seguro
    username: tis
    password: 123456
    driver-class-name: org.postgresql.Driver
  hikari:
    connectionTimeout: 20000
    maximumPoolSize: 10
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
           use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
    open-in-view: false
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s
      additional-exclude: META-INF/VAADIN/config/**
  main:
    lazy-initialization: true
  # enable H2 web console and set url for web console
  # http://localhost:8080/console

logging:
  level:
    org:
      atmosphere : warn
