server:
  port: 5000

# Ensure application is run in Vaadin 14/npm mode
vaadin:
  compatibilityMode : false
  bowerMode : false
  disableUsageStatistics : true

spring:
  datasource:
    url: jdbc:postgresql://tisdbinstance.caagrb8qixzc.us-east-2.rds.amazonaws.com:5432/ebdb
    username: ljosevr
    password: tis12020
    driver-class-name: org.postgresql.Driver
#  hikari:
#    connectionTimeout: 20000
#    maximumPoolSize: 10

  # JPA properties
  jpa:
    hibernate:
     ddl-auto: update
#     ddl-auto: create-drop
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        temp:
           use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
    open-in-view: false
  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  # enable H2 web console and set url for web console
  # http://localhost:8080/console

logging:
  level:
    org:
      atmosphere : warn
